return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "asm",
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "csv",
        "cuda",
        "dockerfile",
        "dot", --Graphviz DOT
        "fish",
        "git_rebase",
        "gitcommit",
        "go",
        "html",
        "javascript",
        "json",
        "lua",
        "make",
        "nasm",
        "python",
        "regex",
        "rust",
        "sql",
        "toml",
        "typst",
        "yaml",
      },
    },
  },
}
