format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$conda\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character
"""

[directory]
style = '#FF7979'

[character]
success_symbol = '[𝞴](#FF7979)'

[git_branch]
style = '#FF7979'
format = '[\[$symbol$branch(:$remote_branch)\]]($style)'
[git_commit]
style = '#FF7979'
[git_state]
style = '#FF7979'
[git_status]
style = '#FF7979'

[cmd_duration]
style = '#FF7979'

[[battery.display]]
threshold = 10
style = 'bold red'

[python]
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'
style = '#FF7979'
